colorscheme gruvbox
set termguicolors
set nu rnu
set expandtab autoindent smartindent
set incsearch hlsearch
set clipboard+=unnamedplus

let mapleader= " "
let g:do_filetype_lua = 1

nnoremap <SPACE> <Nop>


nmap <leader>nt :NvimTreeToggle<CR>
nmap <leader>nf :NvimTreeFindFile<CR>
nmap <leader>nr :NvimTreeRefresh<CR>

nmap <leader>l :BufferLineCycleNext<CR>
nmap <leader>h :BufferLineCyclePrev<CR>
nmap <leader>e :BufferLinePick<CR>
nmap <leader>d :BufferLinePickClose<CR>

nmap <C-p> :Telescope find_files<CR>
nmap <C-s> :Telescope live_grep<CR>
nmap <C-o> :Telescope buffers<CR>
nmap <C-i> :Navbuddy<CR>


nmap <leader>tc :Telescope current_buffer_fuzzy_find<CR>
nmap <leader>tg :Telescope live_grep<CR>
nmap <leader>tt :Telescope treesitter<CR>
nmap <leader>tr :Telescope command_history<CR>
