colorscheme tender
set termguicolors
set nu rnu
set expandtab autoindent smartindent
set incsearch hlsearch
set clipboard+=unnamedplus

let mapleader= " "
let g:do_filetype_lua = 1
nnoremap <SPACE> <Nop>


nmap <leader>nt :NvimTreeToggle<CR>
nmap <leader>nf :NvimTreeFindFile<CR>
nmap <leader>nr :NvimTreeRefresh<CR>

nmap <leader>l :BufferLineCycleNext<CR>
nmap <leader>L :BufferLineMoveNext<CR>
nmap <leader>h :BufferLineCyclePrev<CR>
nmap <leader>H :BufferLineMovePrev<CR>
nmap <leader>j :tabprevious<CR>
nmap <leader>k :tabnext<CR>
nmap <leader>e :BufferLinePick<CR>
nmap <leader>d :BufferLinePickClose<CR>
nmap <leader>bo :BufferLineCloseOthers<CR>
nmap <leader>br :BufferLineCloseRight<CR>
nmap <leader>bl :BufferLineCloseLeft<CR>
nmap <leader>bp :BufferLineTogglePin<CR>
nmap <leader>b1 :BufferLineGoToBuffer 1<CR>

nmap <C-i> :Navbuddy<CR>
nmap <leader>so :Lspsaga outline<CR>

" Keymap for windows manager
nmap <leader>w= :vsplit %<CR>
nmap <leader>w- :split %<CR>
nmap <leader>wc :close<CR>
nmap <leader>wo :only<CR>


nmap <leader>tc :Telescope current_buffer_fuzzy_find<CR>
nmap <leader>tg :Telescope live_grep<CR>
nmap <leader>tt :Telescope treesitter<CR>
nmap <leader>tr :Telescope command_history<CR>
nmap <leader>tf :Telescope find_files<CR>
nmap <leader>tb :Telescope buffers<CR>

nmap <leader>yt :Yazi<CR>
nmap <leader>yc :Yazi cwd<CR>


nmap <F12> :ToggleTerm<CR>
tnoremap <F12> <C-\><C-N>:ToggleTerm<CR>
tnoremap <C-`> <C-\><C-N>
tnoremap <C-[> <C-\><C-N>
tnoremap <C-W> <C-\><C-N><C-W>
tnoremap <A-L> <C-\><C-N>:BufferLineCycleNext<CR>
tnoremap <A-H> <C-\><C-N>:BufferLineCyclePrev<CR>

filetype plugin indent on

autocmd FileType sql,mysql,plsql lua require('cmp').setup.buffer({ sources = {{ name = 'vim-dadbod-completion' }} })
