set -g default-terminal   "screen"
set -g base-index         1
set -g status-keys         vi
set -g mode-keys           vi
set -g mouse              on
set -g focus-events       off
set -s escape-time        10
set -g history-limit      2000
set -g default-command    $SHELL
set -g extended-keys      on
setw -g aggressive-resize off
setw -g pane-base-index   1
setw -g clock-mode-style  12

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
bind-key -T copy-mode-vi 'y' send-keys -X copy-pipe-and-cancel “reattach-to-user-namespace pbcopy”
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key c new-window -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind o if-shell -F '#{window_zoomed_flag}' 'select-pane; resize-pane -Z' 'select-pane'
bind \; if-shell -F '#{window_zoomed_flag}' 'select-pane -l; resize-pane -Z' 'select-pane -l'


# ============================================
# PLUGINS (via TPM)
# ============================================
 
# Install TPM first:
# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
 
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'catppuccin/tmux#v2.3.0'
set -g @plugin 'omerxx/tmux-floax'
set -g @plugin 'sainnhe/tmux-fzf'

# Plugin config
set -g @resurrect-strategy-vim 'session'
set -g @continuum-restore 'on'
 
set -g @catppuccin_flavor 'frappe'
set -g @catppuccin_window_status_style "rounded"
set -g status-left ""
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_pane_default_text "##{b:pane_current_command}"
set -g @catppuccin_window_flags "icon"
set -g status-right "#{E:@catppuccin_status_directory}#{E:@catppuccin_status_session}"

set -g @floax-bind 'f'
set -g @floax-bind-menu 'g'
set -g @floax-text-color 'white'

# Initialize TPM (keep at bottom)
run '~/.tmux/plugins/tpm/tpm'
